### ISSUE TITLE
这个项目的性能怎么样？

### ISSUE THREAD

**Issue by nifflin** [Akagi201/libuv-webserver#1]
你好，我在寻找一款C语言的跨平台的高性能http服务器可编程库，h2o和haywire进入了我的视野。但是各有缺陷，h2o对windows支持不好，haywire性能比h2o低不少，而且不太稳定（这个判断是基于一个基准测试——https://gist.github.com/kellabyte/db163d97cff860ac4485）

我想问问您能提供些建议吗？您的这个项目的性能怎样？能否满足高性能rest接口服务器的开发？

**Comment by Akagi201** [comment]
@nifflerfox 我这东西就是玩玩的, 实际用起来估计很多 bug
